# Generated by Django 4.2 on 2026-07-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('slots', 'Slots'), ('panda_mines', 'Panda Mines'), ('roulette', 'Ruleta'), ('golden_jet', 'Golden Jet'), ('cyber_rolett', 'Cyber Rolett'), ('personajes', 'Personajes')], max_length=50)),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'game_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(max_length=50, unique=True)),
                ('min_bet', models.DecimalField(decimal_places=2, default=0.5, max_digits=10)),
                ('max_bet', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('rtp', models.FloatField(default=0.96)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'game_settings',
            },
        ),
    ]
