# Generated by Django 4.2 on 2026-07-10 05:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_slotsjackpot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotsjackpot',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('400.00'), max_digits=12),
        ),
    ]
