# Generated by Django 4.2 on 2026-07-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_slotsjackpot_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='game_type',
            field=models.CharField(choices=[('slots', 'Slots'), ('farm_fest', 'Farm Fest Slots'), ('duck_rush', 'Duck Rush'), ('panda_mines', 'Panda Mines'), ('roulette', 'Ruleta'), ('golden_jet', 'Golden Jet'), ('cyber_rolett', 'Cyber Rolett'), ('personajes', 'Personajes'), ('dragon_fruit', 'Dragon Fruit Bonanza')], max_length=50),
        ),
    ]
