# Generated by Django 4.2 on 2026-07-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_gameresult_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='game_type',
            field=models.CharField(choices=[('slots', 'Slots'), ('farm_fest', 'Farm Fest Slots'), ('duck_rush', 'Duck Rush'), ('panda_mines', 'Panda Mines'), ('roulette', 'Ruleta'), ('golden_jet', 'Golden Jet'), ('cyber_rolett', 'Cyber Rolett'), ('personajes', 'Personajes'), ('dragon_fruit', 'Dragon Fruit Bonanza'), ('totem_falls', 'Totem Falls Bonanza'), ('golden_sling_rush', 'Golden Sling Rush'), ('frozen_age', 'Frozen Age')], max_length=50),
        ),
    ]
