# Generated by Django 4.2 on 2026-07-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('deposit', 'Depósito'), ('withdrawal', 'Retiro'), ('game_play', 'Juego')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
