# Generated by Django 4.2 on 2026-07-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='method_type',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='token',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='nickname',
            field=models.CharField(default='Mi Tarjeta', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='stripe_payment_method_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(choices=[('card', 'Tarjeta'), ('bank_account', 'Cuenta Bancaria')], default='card', max_length=20),
        ),
    ]
