# Generated by Django 4.2 on 2026-07-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_suspend', 'Suspender usuario'), ('user_ban', 'Banear usuario'), ('modify_settings', 'Modificar configuración'), ('process_withdrawal', 'Procesar retiro'), ('refund', 'Reembolso'), ('bonus_grant', 'Otorgar bono')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_bet', models.DecimalField(decimal_places=2, default=0.5, max_digits=10)),
                ('max_bet', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('welcome_bonus_amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('welcome_bonus_multiplier', models.IntegerField(default=30)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_panel',
            },
        ),
    ]
